version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  prometheus: 
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana: 
    image: grafana/grafana:latest
    volumes: 
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports: 
      - 3000:3000
    links: 
      - prometheus
volumes:
 mongodb:
